spring:
  datasource:
    url: jdbc:mysql://localhost:3306/task_agile?characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false
    username: scott
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: ture
        format_sql: true
        # 여러개 쿼리 나가야할 것을 in으로 한번에 가져옴
        default_batch_fetch_size: 100
server:
  port: 8080