name: CI-CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  S3_BUCKET_NAME: camping-kr
  RESOURCE_PATH: ./src/main/resources/application-real.yml
  CODE_DEPLOY_APPLICATION_NAME: camping-code-deploy
  CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: camping-server

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Set yml file
        uses: microsoft/variable-substitution@v1
        with:
          files: ${{ env.RESOURCE_PATH }}
        env:
#          override.value: ${{ secrets.DI_FROM_SECRET }}
          # override.value: 'from deploy.yaml' <-- 이렇게 사용해도 주입이 된다.
          spring.datasource.url: ${{ secrets.DI_RDS_URL }}
          spring.datasource.username: ${{ secrets.DI_RDS_USERNAME }}
          spring.datasource.password: ${{ secrets.DI_RDS_PASSWORD }}
          jwt.secret: $${{ secrets.DI_JWT_SECRET }}

#      - name: Grant execute permission for gradlew
#        run: chmod +x ./gradlew
#        shell: bash

#      - name: Build with Gradle
#        run: ./gradlew build
#        shell: bash
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Make zip file
        run: zip -r ./$GITHUB_SHA.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$S3_BUCKET_NAME/$GITHUB_SHA.zip

      - name: Code Deploy
        run: |
          aws deploy create-deployment \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --application-name ${{ env.CODE_DEPLOY_APPLICATION_NAME }} \
          --deployment-group-name ${{ env.CODE_DEPLOY_DEPLOYMENT_GROUP_NAME }} \
          --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=$GITHUB_SHA.zip